### ISSUE TITLE
<Feature Request> Stats

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#166]
Hi lcherone, congrats for **### 500** commits!

Within the container tab, some stats are visible, such as CPU time, RAM, and down and upload aggregations. 
So my idea was to add a Stats Tab where some values such as overall CPU Time, Storage size of the whole container, how much Up and Download was over the whole running time, starting with creation.

What do you think about it ?

Best regards
Meywether

**Comment by lcherone** [comment]
Thanks, not bad for a months work ;p..

Disk usage is something I would like to add, for sure, but It will need to be conditional based upon the storage backend.

I didn't add it as the install chooses dir by default, and with dir storage, it does not support displaying disk status values (size, usage etc). Which is when people will report it as a bug that it does not show anything, or ask for some other storage to be the default, which I want to do but it involves testing it, that it won't be a house of cards and cause more issues btrfs is out of the window, so its most likely zfs, but then 2 more issues begin, storage driver is not usable inside a container and can only restore from most recent snapshot. Which throws running the panel nested and need functionality added to snapshots section to prevent restoring from an older snapshot.
I've added the code to check on the LXD extensions but not got around to fine tuning, things like this.

Other stats, if they are not supplied by LXD or from the Plinker System Component, then they won't be added as I don't want to get into constantly polling the system/containers for data, maintaining a database to check for persistent values and averages etc.. I've done panels like this before, and databases can get huge and because its a simple SQLite db, I dont want to cause read/write blocking.. 

Plus for the most part, people don't seem to look at the stats.. a comment on another site, said "the panels shit, 23% CPU usage on a clean system!!!" ~ But didn't think to look at processes panel to see why.. Or installs on localhost and expects an idle system because they got no containers.. whilst there moving their mouse around or expect no ram when 30+ chrome windows open.

**Comment by Meywether** [comment]
Haha ! I knew that problem you mention!
Ok, was an idea! I get your points! 
Thanks a lot !

**Comment by lcherone** [comment]
Sidenote the launch container process I'm working on is sweet now, utilising operations more to get the status of things.. which will make the UX for that nicer. Lots still todo/test but heres a screen...

![peek 2018-06-20 20-14](https://user-images.githubusercontent.com/3892806/41679631-c1dc2f94-74c6-11e8-86fc-9fc223ead2bc.gif)

**Comment by Meywether** [comment]
Nice Nice !! Sometimes, when many people are at my network I got an error "container could not be created" but after some times (the operation was still running) everything was fine. Thanks a lot, thats a really nice feature !!1

**Comment by lcherone** [comment]
I've merged the changes to creation, so should all be good now.

**Comment by Meywether** [comment]
whoops :) we will see, gonna check it

**Comment by Meywether** [comment]
👍
